### ISSUE TITLE
Animations in Internet Explorer not working

### ISSUE THREAD

**Issue by kadoogan55** [live-composer/live-composer-page-builder#336]
There is an issue with Internet Explorer when using animations with text and photos - Explorer does not recognize the animations.

This results in everything that has animations applied being out of position. In fact, they are in the starting position for the given animation that is applied.

The CSS code I had that was working in resolving this issue (which simply turned off selected animations completely in Explorer) no longer works. I have since found out this is a result of the library for browser detection being deleted in version 1.2 (I believe).

The CSS code that WAS working is as follows:

@media all and (-ms-high-contrast: none), (-ms-high-contrast: active) {.win.gecko .dslc-in-viewport-anim-dslcSlideRightFadeIn.dslc-in-viewport-check, .win.gecko .dslc-in-viewport-check.dslc-in-viewport-anim-dslcSlideLeftFadeIn, .win.gecko .dslc-in-viewport-check.dslc-in-viewport-anim-dslcSlideUpFadeIn, .win.gecko .dslc-in-viewport-check.dslc-in-viewport-anim-dslcSlideRightFadeIn, .win.gecko .dslc-in-viewport-check.dslc-in-viewport-anim-dslcSlideLeftFadeIn { transform: none !important; }
}

Obviously due to the library being deleted, the above code can no longer work.

So I am hoping for a new solution - soon I hope - I have several sites out there that are now having this issue, and Internet Explorer still holds about 1/4 of the browser market at this time.

Perhaps there is a way to get the cancelled animation in Explorer to show up the end of the animation instead of the beginning (which is what it is doing now, causing animated text and images to appear out of position).

One of a few sites I am having issues with because of this is:

http://www.vanko.net

This may help some who are looking at this post understand the issue - try it out in Chrome or FF, then try it in Explorer

**Comment by mozalan** [comment]
No reply yet?... Me and 7 of my colleagues who are in the design business, facing the same issue with IE not rendering pages correctly due to this library thing... it's very urgent.

**Comment by lumberman** [comment]
@mozalan do you know what IE versions affected?

**Comment by lumberman** [comment]
Guys, please try this version https://github.com/live-composer/live-composer-page-builder/archive/issue/336.zip

MAKE SURE TO CREATE A FULL BACKUP!

I have no IE installed on my machine and have no access to a virtual machine to test it.

**Comment by kadoogan55** [comment]
Sorry, just noticed the updates. Will test later today.

**Comment by kadoogan55** [comment]
IE versions were 11 an an unknown older version.

**Comment by lumberman** [comment]
Looking forward to see results of testing.
Make sure to create a full backup.

**Comment by kadoogan55** [comment]
Too busy yesterday. Trying again today.

**Comment by kadoogan55** [comment]
I created a new test site in Flywheel and tried it out - didn't work!  :(

I tried adding the CSS using a plugin I like called Duo Leaf CSS but that did not work, neither did adding the CSS code directly to the HEADER.PHP file.

It also does not work without the code.

The code I tried is as follows in IE 11:
<meta http-equiv="X-UA-Compatible" content="IE=7,8,9,10,11">

I have uploaded a screen cap of it - the white text in the blue box should be centred vertically.

Hope you guys can figure this out - it used to work in older versions of LC.

![stylecapture_2016-10-26_13-30-17_226](https://cloud.githubusercontent.com/assets/20845695/19742194/15b778ba-9b81-11e6-8782-8fb1a2f06aee.jpg)

**Comment by kadoogan55** [comment]
I should mention that I wasn't sure the extra code was necessary, so that is why I tried it with and without it.

**Comment by kadoogan55** [comment]
I think it's safe to say that we really need a resolution on this that has become a major issue. Many users including myself are awaiting this fix. I have clients asking me what's going on and I have no answers for them. Please help as soon as possible.

**Comment by lumberman** [comment]
Tomorrow my developer will check it and hopefully fix it.
He has a Windows-powered machine available for testing.

**Comment by kadoogan55** [comment]
Thank you! 

Thought I would also mention that the problem was initially caused by a deletion of the library for browser detection on your end. The one that was adding .win.gecko classes. 

not sure if that got mentioned by anyone prior. This all started out on the LC Facebook site initially.

**Comment by lumberman** [comment]
Yes, we know it. It wasn't the best solution to keep a whole library in the code to fix the single bug in IE. We will fix it tomorrow without a need to use additional libraries.

**Comment by kadoogan55** [comment]
I can hardly wait - it will be nice to have LC back! I can't use it without that functionality. 

I understand your reasoning behind ditching the library, but without a replacement fix it was kind of a disaster. 

Thank you!

Dave

**Comment by lumberman** [comment]
@kadoogan55 can you check the code in https://github.com/live-composer/live-composer-page-builder/archive/issue/336.zip ?

**Comment by kadoogan55** [comment]
Do I need to add any code or does this just work as is?

**Comment by lumberman** [comment]
Should be working as is.

**Comment by mozalan** [comment]
I've just tested, I'm afraid it's still the same, not just about the animations side of it, but images are not rendered correctly - causing large images to stay large and everything overlaps... 

Please check the attached screen shot.. thanks.
![for vlad](https://cloud.githubusercontent.com/assets/20672449/20039193/ca5c8d6e-a437-11e6-8334-0316f37be377.PNG)

**Comment by lumberman** [comment]
@mozalan images are another story. What about animations? 

- What version of the browser you have?
- Are you sure to test https://github.com/live-composer/live-composer-page-builder/archive/issue/336.zip not master?

@xdima92x Please follow-up with guys here. I know you tested it in IE, but I want to make sure there are no versions or cases with broken functionality. Thanks!

**Comment by xdima92x** [comment]
Hi @lumberman I've tested the LC in IE - https://github.com/live-composer/live-composer-page-builder/archive/issue/336.zip. It's a bug. I also have this problem - https://www.evernote.com/shard/s554/sh/631e29e3-d13b-4d92-93bf-344bf265c4ba/0f980b28a4746545

**Comment by lumberman** [comment]
@xdima92x I thought that you fully tested animations in IE?
We are not talking about pictures now, only animations.

**Comment by kadoogan55** [comment]
He had mentioned in his earlier post that the animations were not working, in addition to the photos not rendering properly. I have yet to be able to test the animations but will soon.

**Comment by kadoogan55** [comment]
Trying to test over the next day or two but sounds like it is not working.

**Comment by mozalan** [comment]
Non of it works, not Animations, nor Image rendering... it's a big mess right now, I've got many of my customers complaining and wanting me to stop using LC on their projects because of this issue.. 

I don't know about the USA but in the United Kingdom, more than 90% of computer / notebook users are on Windows 7 - with Internet Explorer 11... so it's a very big problem ...

**Comment by mozalan** [comment]
Can we please make sure this gets a priority mark on it so it could be resolved asap? If needs be, please provide the package with old IE library enabled so whoever wants to use that, would be able to still use it. I don't know if it's something would be addresses on a new update of LC but it's a deal breaker at the moment...

**Comment by kadoogan55** [comment]
Worldwide IE is still being used to a fair degree - fair enough to be a deal breaker for sure.

**Comment by lumberman** [comment]
Guys, if you have new issues, please open new issue for these.
There is no way to fix more then one bug per commit and we link commits with issues.

If you confirm that the problem with animations solved – I close the issue and merge code with the master branch.

Any other problems will be solved in new threads. Thanks again for your help.

PS: I work on Mac and don't have windows to test product on. From your comments, looks like there are issues, so I will try to find virtual machine with Windows and install it before publishing next update. As aways please crate issues and describe problems. We are willing to solve it for you.

**Comment by kadoogan55** [comment]
I finally got around to testing the animations - it works! Sorry for not getting it tested sooner, and thanks for getting it figured out!

**Comment by kadoogan55** [comment]
I know this is closed but I am wondering if the animation fix for IE was ever rolled into the current version of Live Composer. I updated my client site to the latest version but the animation issue didn't seem to be fixed.
You can see it at http://www.vanko.net/main/

**Comment by Dudaevskiy** [comment]
+1
