### ISSUE TITLE
Button icons always displaying

### ISSUE THREAD

**Issue by Deanphillips** [live-composer/live-composer-page-builder#338]
Hey guys,

On the latest version, the icons on buttons are always displaying now (even when turned off)

This is in the icon box

**Comment by lumberman** [comment]
Dean, can you please check the latest code in the master branch?
https://github.com/live-composer/live-composer-page-builder/archive/master.zip

**_SITE BACKUP REQUIRED_**

**Comment by Deanphillips** [comment]
I've tried this and it's still not working:

http://skinnytosuperhero.com/body-type/

<img width="699" alt="screenshot 2016-10-21 16 33 26" src="https://cloud.githubusercontent.com/assets/21025321/19610751/1f2c2842-97ac-11e6-9590-cbf4db26490b.png">

**Comment by lumberman** [comment]
Should be fixed now.

**Comment by Deanphillips** [comment]
This still isn't working.

Do I have to put anything as the settings to make sure there's no icon?!

**Comment by lumberman** [comment]
Under Styling > Icon tab you have a switch Enabled/Disabled. Can you check this one please?

**Comment by Deanphillips** [comment]
It looks like there's only one on the secondary button?!

**Comment by Deanphillips** [comment]
This isn't fixed still (tried the latest version) 

<img width="580" alt="screenshot 2016-10-29 13 40 32" src="https://cloud.githubusercontent.com/assets/21025321/19829568/491d2cd2-9ddd-11e6-82a3-5589ed2cacb4.png">
