### ISSUE TITLE
Archive template deletion issue

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#422]
When an "Archive template" is deleted (sent to trash) is still displayed on the website (live). The template is not applied anymore once the template is permanently deleted.

**Comment by lumberman** [comment]
I think it fixed in the master branch.
Can you please check it and close the ticket if fix confirmed?

**Comment by FoldingTheme** [comment]
@lumberman the problem is still present in the master branch.

**Comment by xdima92x** [comment]
Hi @FoldingTheme and @lumberman I downloaded the latest code from the master branch https://github.com/live-composer/live-composer-page-builder/archive/master.zip. It works. I recorded a short video - https://drive.google.com/file/d/0B7nJlmCX4yHueUJDdl9ualZkeTg/view

**Comment by FoldingTheme** [comment]
@xdima92x great!
