### ISSUE TITLE
Problem with styling presets and default values

### ISSUE THREAD

**Issue by BobaWebDev** [live-composer/live-composer-page-builder#584]
How to replicate:

1. Add 2 social modules
2. Give them both a styling preset ( the same preset )
3. On the second module remove the default value ( # ) for twitter ( or fb or youtube ) and save
4. On the first module add a value to any of the options
5. Save and Publish changes
6. Refresh and the second module will get back the default value for twitter that was removed

So, it has something to do with presets and the default values for options. Most likely related to that new system the LC data is stored with, I noticed that it contains default values, previously the default values were not part of the data, now they are ( it also makes the data a LOT larger than it used to be ).

**Comment by BobaWebDev** [comment]
Any info on this?

**Comment by ktotten** [comment]
This is a huge problem on the site I designed for Artelements.net, on the Contributors page. It is showing empty Youtube and other icon links and I'm getting complaints. Can we please get a resolution (fix) soon?

**Comment by xdima92x** [comment]
https://github.com/live-composer/live-composer-page-builder/tree/issue/584

**Comment by xdima92x** [comment]
Bug is fixed but you need to resave broken modules. Sorry for this issue.

**Comment by mozalan** [comment]
This is still an issue, trying to add more than one PRESET to Text Element and it keeps getting corrupted after just 2 uses, third box gets corrupted and that effects the others, please test before implementing.
