### ISSUE TITLE
Google Map + Cache

### ISSUE THREAD

**Issue by xdima92x** [live-composer/live-composer-page-builder#755]
https://drive.google.com/file/d/0B7nJlmCX4yHuNnFhSjExSV96OEE/view

**Comment by lumberman** [comment]
Fixed in https://github.com/lumbermandesigns/lc-googlemaps/issues/2

**Comment by Viktor6713** [comment]
Hi, we are using Live Composer with WP Google Maps and this is still an issue. First time map is loaded and displayed normally, on the second page reload no map. After cleaning cache map is displayed first time only, when we disable "Basic HTML/CSS Caching" map is displayed every time.
We've tested other map plugins with the same result.
