### ISSUE TITLE
Categories/Posts Messing Up (Reverting to Defaults on First Post/Category)

### ISSUE THREAD

**Issue by emingus** [live-composer/live-composer-page-builder#784]
I'm going to do my best to explain what happened on my site and another site that is hosted on a different server. (GoDaddy & Siteground respectively).

When I install the new update, the VERY FIRST blog post on the home page goes to an unstyled category page (only my header is applied).

Then the FIRST CATEGORY listed in my navigation seem to go the "right" url BUT it goes to my latest blog post that i unstyled (only my header is applied).

If I'm logged in, the "Edit Template" is listed as available to edit on both the category page and the blog post page.

This doesn't happen on the second posts on my homepage or the second link in my navigation.

NOTE: 
I deactivated every single plugin
I changed to Twenty-Seventeen theme
Deleting the module within page and redoing it.
Deleting LC via FTP and Reinstalling Live Composer
Disabling all plugins to no avail.
Recreating templates of blog post, archives, category pages, search pages.

I fixed it by installing an older version of LC, but I'd like to update!

**Comment by lejardindeden** [comment]
Your problem looks similar to mine. (Issue #778)
So I tried the different steps you did. And I have the same result,. I fixed it with a version >=1.3.1 of LC.
( The problem comes with the release 1.3.2 of LC )

My template for single and archive does not look to mess up anymore.

When I use LC 1.3.2 and update my archive template, my last post use the archive template without styling. The others posts works normally by using the single template.

Which difference between the version 1.3.1 and 1.3.2 makes this problem appears ?

Thank you for helping us on this issue.

**Comment by FoldingTheme** [comment]
The problem remain on the first listing from a search results page.

**Comment by xdima92x** [comment]
Hi @FoldingTheme Thanks. Fixed - https://github.com/live-composer/live-composer-page-builder/tree/issue/784_ver2

**Comment by xdima92x** [comment]
**Notice:** Check when migration
