### ISSUE TITLE
Module “Blog element” is not filtering posts by category

### ISSUE THREAD

**Issue by JaimeUNA** [live-composer/live-composer-page-builder#969]
Module “Blog element” is not filtering posts by category. This happened after the last update.

**Comment by xdima92x** [comment]
@JaimeUNA Hi) Did you try to use this option?
![_ _121718_020524_pm](https://user-images.githubusercontent.com/21044637/50086191-eebd0300-0204-11e9-86d4-8747a2f76c3a.jpg)

**Comment by JaimeUNA** [comment]
Hi, yes, I checked this option, but the problem was solved by unchecking and re-tagging the categories I wanted to filter. After selecting the option indicated in the image I had to do this procedure to work. Thank you for the tip.

**Comment by xdima92x** [comment]
It's good :)

**Comment by JoseAGRSa** [comment]
This still happens to me even after doing what you recommended. Previous versions also dont work because when i try to install them, a error saying "No plugin file" appear

**Comment by L1lle** [comment]
I solved it by  just changing the value for "Filter Posts By" one time from "Categories" to "Tags" and back.

**Comment by JoseAGRSa** [comment]
Hi @L1lle and @xdima92x. What @L1lle said works but it's not a viable option for me because i have hundreds of blog elements.

**Comment by bandicootmarketing** [comment]
Hi @JoseAGRSa - please try just switching the "Filter Post by" from "Category" to "Tag" and back, without saving in between. Let us know!

**Comment by JoseAGRSa** [comment]
Hi @bandicootmarketing! I tried that and yes, it works but, like i said above, i have hundreds of blog elements.
Do will lunch an updated version where i wouldn't need to do that?

**Comment by bandicootmarketing** [comment]
@JoseAGRSa yes we have actually discovered a few other fixes we need to make so we will be pushing another update to the .org repo here in the next few days.

**Comment by xdima92x** [comment]
Hi guys) We fixed it. We will update soon LC. You can use this branch (master) - https://github.com/live-composer/live-composer-page-builder
